### PR TITLE
Compiles with Coq 8.7 and 8.8.

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by CohenCyril** [comment]
Hi! Thank you for the PR! Which version/repository do you use for paramcoq?

**Comment by proux01** [comment]
For 8.7: https://github.com/aa755/paramcoq/tree/v8.7
For 8.8: https://github.com/aa755/paramcoq/pull/7

**Comment by CohenCyril** [comment]
> For 8.7: https://github.com/aa755/paramcoq/tree/v8.7

according, to travis, this version of paramcoq does not compile wrt coq.8.7.2, which version of coq.8.7 do you use?

**Comment by proux01** [comment]
Sorry, looks like I was using a slightly modified version. I just filled a PR https://github.com/aa755/paramcoq/pull/8

While waiting for the PR to be merged, I changed the PARAMCOQ_URL in travis test script
(but it seems I failed relaunching the test).

**Pull request merged**
