### PR TITLE
Switch to meta.yml

### PR DESCRIPTION
**Pull request by proux01**
C.f. https://github.com/coq-community/templates

### CODE REVIEW

**Comment by CohenCyril** [comment]
The best practice (for the next time) is to push in an upstream branch which is not master in order to test the new CI config, before merging in master.

**Comment by proux01** [comment]
The CI got through (c.f. the little green check just on the left of the commit hash above)

**Comment by CohenCyril** [comment]
I thought that PR from branches outside the main repository could not modify github actions. Maybe I'm wrong, I will look into it.

**Comment by proux01** [comment]
> Guillaume Cano and Vincent Siles are original authors as well

Fixed

**Pull request merged**
