### PR TITLE
Update the Travis CI configuration

### PR DESCRIPTION
**Pull request by erikmd**
Summary:
* Also test CoqEAL against coq-8.9 (cf. math-comp/docker-mathcomp#1) and mathcomp-dev
* Fix the script involving `set -e` and `&&` (cf. commit message)

BTW if the CI is OK with this PR, @CohenCyril could you prepare an opam package for CoqEAL? that would be really great! :+1:

Cc @proux01

### CODE REVIEW

**Comment by CohenCyril** [comment]
> BTW if the CI is OK with this PR, @CohenCyril could you prepare an opam package for CoqEAL? that would be really great!

On my todo list of this week :smile:

**Comment by CohenCyril** [comment]
@erikmd I fixed the opam for the released versions of multinomial. Let us see what happens now...

**Comment by erikmd** [comment]
Thanks @CohenCyril!
We'll be able to relaunch the build, but before that @proux01 just told me the computed version of `coq-paramcoq` seemed too old when using `coq.dev`, so maybe we can wait that there is a `coq-paramcoq.dev` package before relaunching the build?
Thanks again!

**Comment by erikmd** [comment]
coq/opam-coq-archive#575 has been merged, so I'll try to restart the build by closing/reopening the PR…

**Comment by erikmd** [comment]
The build is still failing, and I don't understand why `opam` cannot find `coq-paramcoq.dev`:

```
$ docker run --rm -it mathcomp/mathcomp:1.7.0-coq-dev
coq@6b46be58d521:~$ opam update -y >/dev/null
coq@6b46be58d521:~$ opam repo list
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured
       repositories.

<><> Repository configuration for switch 4.05.0 <><><><><><><><><><><><><><><><>
 1 coq-core-dev  https://coq.inria.fr/opam/core-dev
 2 coq-extra-dev https://coq.inria.fr/opam/extra-dev
 3 coq-released  https://coq.inria.fr/opam/released
 4 default       https://opam.ocaml.org
coq@6b46be58d521:~$ opam show coq-paramcoq

<><> coq-paramcoq: information on all versions ><><><><><><><><><><><><><><><><>
name         coq-paramcoq
all-versions 1.0.5  1.0.6  1.0.9  1.1.0  1.1.1+coq8.7  1.1.1+coq8.8  1.1.1+coq8.9

[…]
```

@proux01 do you think there were an issue with the metadata of coq/opam-coq-archive#575 ?

**Comment by proux01** [comment]
> @proux01 do you think there were an issue with the metadata of [coq/opam-coq-archive#575](https://github.com/coq/opam-coq-archive/pull/575) ?

No, it seems to be an issue in the publication of the opam repo: https://github.com/coq/opam-coq-archive/pull/575#issuecomment-462320759

**Comment by erikmd** [comment]
FYI @CohenCyril the build went farther, and stopped at the following 2 issues:

* `mathcomp/mathcomp:1.7.0-coq-dev`: nested proof issue in `./ssralg_ring_tac.v` [(build log)](https://travis-ci.org/CoqEAL/CoqEAL/jobs/491700922#L1912-L1916)
* `mathcomp/mathcomp-dev:coq-8.7`:  coq-mathcomp-finmap.1.1.0 FTBFS with mathcomp-dev [(build log)](https://travis-ci.org/CoqEAL/CoqEAL/jobs/491700923#L1483-L1499)

**Comment by erikmd** [comment]
Hi @CohenCyril, the first issue is resolved (it basically sufficed to add some `:= {}` given coq/coq#9274).

It remains the issue with `coq-mathcomp-finmap.1.1.0`…

(and later on you might want to relax some constraints in `coq-mathcomp-multinomials.1.x.dev` to avoid this [if-then-else](https://github.com/CoqEAL/CoqEAL/blob/aedd02e3174d0be93a05f2cbcc70ebc902e5f6ef/.travis.yml#L38-L40))

**Comment by erikmd** [comment]
Dear @CohenCyril, the dependencies of CoqEAL should now be compatible with mathcomp-dev at the Coq level, but before restarting the build it seems some extra changes have to be done at the opam level:

* Editing https://github.com/math-comp/finmap/blob/master/opam:
  * `"coq-mathcomp-ssreflect" {(>= "1.6" & < "1.8.0~") | (= "dev")}`
* Creating (in https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/) `coq-mathcomp-finmap/coq-mathcomp-finmap.dev/opam`:
  * from https://github.com/math-comp/finmap/blob/master/opam
* Editing https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-mathcomp-multinomials/coq-mathcomp-multinomials.1.x.dev/opam:
  * `"coq-mathcomp-ssreflect" {(>= "1.6" & < "1.8.0~") | (= "dev")}`
  * `"coq-mathcomp-algebra" {(>= "1.6" & < "1.8.0~") | (= "dev")}`
  * `"coq-mathcomp-finmap" {(>= "1.1.0" & < "1.2.0~") | (= "dev")}`

**Comment by erikmd** [comment]
Hi @CohenCyril, thanks a lot for all your work on releasing math-comp and CoqEAL!
The `.travis.yml` in `master` is up-to-date so I can now close this PR.

**Pull request closed without merging**
