### PR TITLE
A few extra functions about seqmx.

### PR DESCRIPTION
**Pull request by proux01**
A few additional functions that were required for our development with erikmd.
Some might be too specific for inclusion into CoqEAL, feel free to choose.

P.S. : depends from previous PR about seqmx by erikmd.

### CODE REVIEW

**Comment by proux01** [comment]
Update to latest version of branch paramcoq-dev.

**Comment by VHarisop** [comment]
Hi @proux01 ,

would you mind sharing a few examples using `fun_of_of`? From what I understand, it is supposed to cover elementwise access to elements of a matrix, however the following fails:

```
Import GRing.Theory.

From mathcomp Require Import ssrint matrix.
From CoqEAL Require Import binint binord.

Definition M := 'M[int]_(2) := \matrix_(i, j < 2) (i + j * i)%:Z.

Goal (@fun_of_matrix int _ _ Maddm ord0 ord0 == 0).
Proof.
  Fail by coqeal. (* fails with Error: Could not fill dependent hole in "apply" *)
Abort.

**Comment by proux01** [comment]
Hi @VHarisop ,

I never used the coqeal tactic. I guess it works well when you have carefully built all yout typeclass instances beforehand. Here, there is certainly something missing (about ordinals ?). A first step to try
to guess what could be to first do the proof by hand:
`From mathcomp Require Import ssreflect ssrint fintype matrix.                                                                                                                             
From CoqEAL Require Import param refinements seqmx.                                                                                                                                       
                                                                                                                                                                                          
Require Import seqmx_complements.                                                                                                                                                         
                                                                                                                                                                                          
Typeclasses eauto := debug.                                                                                                                                                               
                                                                                                                                                                                          
Existing Instance implem_ord.                                                                                                                                                             
                                                                                                                                                                                          
Definition M3_seqmx : hseqmx 2 2 :=                                                                                                                                                       
  seqmx_of_fun (fun _ _ : 'I_2 => 3%:Z).                                                                                                                                                  
                                                                                                                                                                                          
Goal (fun_of_matrix M3 ord0 ord0 = 3%:Z).                                                                                                                                                 
Proof.                                                                                                                                                                                    
replace (M3 _ _ ) with (fun_of_seqmx M3_seqmx 0 0).                                                                                                                                       
{ by vm_compute. }                                                                                                                                                                        
symmetry.                                                                                                                                                                                 
apply refinesP.                                                                                                                                                                           
eapply refines_apply.                                                                                                                                                                     
{ eapply refines_apply.                                                                                                                                                                   
  { eapply refines_apply.                                                                                                                                                                 
    apply (Rseqmx_fun_of_seqmx (nat_Rxx 2) (nat_Rxx 2)).                                                                                                                                  
    apply Rseqmx_seqmx_of_fun.                                                                                                                                                            
    by rewrite refinesE. }                                                                                                                                                                
  by rewrite refinesE. }                                                                                                                                                                  
by rewrite refinesE.                                                                                                                                                                      
Qed.`

Maybe @CohenCyril and other CoqEAL authors could be more precise.

**Comment by VHarisop** [comment]
Hi @proux01, thanks a lot for taking the time to look into this.
The missing piece seems to be the following premise of `RseqmxC_seqmx_of_fun` (in `seqmx.v`):

```
`{forall x y, refines (rI rm) x y ->
  forall z t, refines (rI rn) z t  -> refines (rAC \o (@unify _)) (f x z) (g y t)}
```

We're still not sure how to introduce this missing piece for ordinals, but hopefully it won't be something too difficult.

**Comment by VHarisop** [comment]
Hi again @proux01,

the following example works for me, after introducing a trivial refinement. I'm still not sure why this was not properly handled when importing `binord`.

```
From mathcomp Require Import all_ssreflect fintype ssrint matrix.
Require Import hrel param refinements seqmx seqmx_complements.

Existing Instance implem_ord.

Instance refines_ord_num {n} (m : 'I_n) :
  refines (Rord (nat_Rxx n)) m m.
Proof. by rewrite refinesE. Qed.

Definition Mp := \matrix_(i, j < 3) (i + j * i)%:Z.

Goal (Mp ord0 ord0 = 0).
Proof.
  by coqeal.
Abort.

Goal (Mp (Ordinal (erefl (1 < 3))) ord0 = 1%:Z).
Proof.
  by coqeal.
Abort.

Goal (Mp (Ordinal (erefl (2 < 3))) (Ordinal (erefl (1 < 3))) = 4%:Z).
Proof.
  by coqeal.
Abort.
```

**Comment by proux01** [comment]
Congrats @VHarisop 

I wonder whether there is a good reason not to add it a s a global instance in CoqEAL or if it would be harmless.

Btw, the `Existing Instance implem_ord` does not seem required.

**Comment by VHarisop** [comment]
@proux01 At least in my toy implementation, I've moved `refines_ord_num` in `seqmx_complements.v` without any harmful side-effects so far. You are right about removing the `Existing Instance ...` line.

**Pull request merged**
