### PR TITLE
Compile with Coq master and mathcomp.1.9.0

### PR DESCRIPTION
**Pull request by proux01**
This should be backward compatible. Let's wait for confirmation by the CI.

### CODE REVIEW

**Comment by erikmd** [comment]
@proux01 thanks for your PR! (the `mathcomp/mathcomp:1.9.0-coq-dev` image is not yet built but I promised @CohenCyril to prepare it very soon)

**Comment by erikmd** [comment]
@CohenCyril I've refactored the documentation of the tool we were talking about at the beginning of the week (https://github.com/erikmd/docker-hub-helper#use-cases) and the build of the image `mathcomp/mathcomp:1.9.0-coq-dev` (based on coq/opam-coq-archive#779) is now in progress.

I'll just need to automate the rebuild of this image on a daily basis (like `coqorg/coq:dev`) and document further all this. I'll let you informed ASAP.

**Comment by erikmd** [comment]
@proux01 done (`mathcomp/mathcomp:1.9.0-coq-dev` is ready)

**Comment by proux01** [comment]
CI green

Everything seem ok at Coq level.

At opam level, some `= dev` are missing in finmap and multinomials, hence the orrendous use of opam option `--ignore-constraints-on`

**Comment by CohenCyril** [comment]
> At opam level, some `= dev` are missing in finmap and multinomials, hence the orrendous use of opam option `--ignore-constraints-on`

This is deliberate, I do not wish that opam packages depend on dev version, but for testing it make sense to ignore constraints so as to test precisely things that are not meant to always be stable at all times.

**Comment by proux01** [comment]
This is you code, you take the decision.

But just let me express my point of view (mostly shared with @erikmd if I'm not mistaken):
* casual users only use the `-released` repository, so they just don't see the dev packages which aren't an issue for them;
* dev packages mostly target developers who want to test their code with a mix of dev and last released package (just like here), that's where these `| (= dev)` constraints become handy;
* their absence can be somewhat overcome using `--ignore-constraints-on` but it's a pretty inconvenient workaround, doing this, you have to repeat this option on any subsequent opam command for opam to be able to find solutions and it basically means using opam without any management of dependencies, which is a large part of the goal of using a package manager.

Anyway, back to the current PR, I think it's ready and can be merged.

If you want to readd mathcomp-dev to the CI, feel free to do it but I gave up, sorry about that.

**Comment by CohenCyril** [comment]
@proux01 the problem is when packaging development version for opam coq archive: it happened to me several times that opam coq archive CI fails and the only fix I could find was to simply exclude dev versions from dependencies (the alternative being: making all required dev version at the time of insertion of the package compile together). How do you and @erikmd deal with that?

**Comment by erikmd** [comment]
@CohenCyril I believe I see what you mean (i.e., the opam-coq-archive could install the most recent version of a dependency of a `released` package, namely the `dev` version of the dependency which is not guarantee to stay compatible).

However, I did not encountered that issue and so far I don't think it can occur in practice, because:
* the development versions of Coq and third-party libraries is not in `released`
* and the opam-coq-archive CI doesn't add the `core-dev` or `extra-dev` repos inconditionally,
  cf. https://github.com/coq/opam-coq-archive/blob/dae1d2121a23eedcfe1b2468390540ee796a3337/scripts/opam-coq-install-remove#L52-L66

To give a concrete example, when I relaxed the constraint of the `coq-mathcomp-ssreflect.1.9.0` package here, to allow `coq.dev`:
https://github.com/coq/opam-coq-archive/pull/779/files#diff-5cf74f0814286cde1dafbff07d06f32e
the corresponding CI job never tested this package with `coq.dev`:
https://gitlab.com/coq/opam-coq-archive/-/jobs/225220755 − «grep "install coq"»

So I guess we should be on a safe side even if the `released` packages allow `(= "dev")`…

Do you agree or am I missing anything?

**Comment by CohenCyril** [comment]
> Do you agree or am I missing anything?

Then I am ok with adding coq "dev" as a dependency. Unless I am mistaken what I mentioned is a problem only for dependencies in packages (e.g. mathcomp dev, finmap dev, etc...)

**Comment by erikmd** [comment]
Hi @CohenCyril 
> I am ok with adding coq "dev" as a dependency. Unless I am mistaken what I mentioned is a problem only for dependencies in packages (e.g. mathcomp dev, finmap dev, etc.)

I might be wrong, but AFAICT there should be no difference between adding a `coq.dev` resp. `finmap.dev` dependency in a package submitted in opam-coq-archive's **released**, because `finmap.dev` will be gathered in **extra-dev**, in the same way as `coq.dev` is gathered in **core-dev**, so that both dev dependencies won't be picked by the CI when checking one such PR for released…

**Comment by CohenCyril** [comment]
> I might be wrong, but AFAICT there should be no difference between adding a `coq.dev` resp. `finmap.dev` dependency in a package submitted in opam-coq-archive's **released**, because `finmap.dev` will be gathered in **extra-dev**, in the same way as `coq.dev` is gathered in **core-dev**, so that both dev dependencies won't be picked by the CI when checking one such PR for released…

@proux01 @erikmd I completely lost track of this. When could we talk about this (on the phone/skype/whatever)?

**Comment by erikmd** [comment]
Hi Cyril, I won't be in Toulouse next week but we plan to meet with Pierre on Wed 24 July afternoon... would you be available at that moment so we can talk on the phone?

**Comment by CohenCyril** [comment]
Ok

Le 13 juillet 2019 13:42:15 GMT+02:00, Erik Martin-Dorel <notifications@github.com> a écrit :
>Hi Cyril, I won't be in Toulouse next week but we plan to meet with
>Pierre on Wed 24 July afternoon... would you be available at that
>moment so we can talk on the phone?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/CoqEAL/CoqEAL/pull/19#issuecomment-511115428

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Pull request merged**
