### PR TITLE
Add a few operators to binrat (refinement of rat by bigQ)

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by proux01** [comment]
CI green, @CohenCyril would you allow me to merge this, do a release and the OPAM package or would you prefer to have a look first / do it yourself?

**Comment by CohenCyril** [comment]
@proux01 sure, you can go ahead.
- I would be in favour of a transition to a `meta.yml` generated meta data.
- You might want to give a try to https://github.com/coq-community/templates/pull/91

**Comment by proux01** [comment]
> * I would be in favour of a transition to a `meta.yml` generated meta data.

good point, done

> * You might want to give a try to [coq-community/templates#91](https://github.com/coq-community/templates/pull/91)

I'll be happy to try it once the required release of multinomials will have happened : https://github.com/math-comp/multinomials/pull/38

**Comment by proux01** [comment]
> * You might want to give a try to [coq-community/templates#91](https://github.com/coq-community/templates/pull/91)

So I just tried it, it's nice, a few minor comments:
* I had to update from OPAM 2.0.3 to 2.0.5, an opam version check would be great, but definitely a detail
* I had to `git config --add github.user <user>` otherwise the call to `git config` makes the whole script fail (on line 59, without error message, whatever the options provided)
* I would love an option to use an already existing clone of coq-opam-archive, the clone takes both bandwidth and time

**Comment by CohenCyril** [comment]
Thank you very much for trying. Could you tell me what failed with opam 2.0.3 ?

**Comment by proux01** [comment]
The lint option `check-upstream` did not exist (it may exist in 2.0.4, haven't tried).

**Comment by CohenCyril** [comment]
> * I would love an option to use an already existing clone of coq-opam-archive, the clone takes both bandwidth and time

I will definitely provide this option. Note that you can also use `--depth n` (start with n=1 and increase if it does not work) to do a shallow clone (it may fail because sometimes pushes of branches from clones that are too shallow are rejected by github)

**Pull request merged**
