### PR TITLE
MathComp 1.12

### PR DESCRIPTION
**Pull request by proux01**
Also replace Travis CI by Github Action.
EDIT Cyril:
closes #31 which was a duplicate for CI purposes

### CODE REVIEW

**Comment by proux01** [comment]
Github action doesn't seem to even start, @erikmd would you have any idea what I made wrong?

**Comment by CohenCyril** [comment]
> Github action doesn't seem to even start, @erikmd would you have any idea what I made wrong?

Github actions cannot be activated by PR from outside of the main repo...

**Comment by proux01** [comment]
Thanks! Could you please do a minor release (I'll take care of the OPAM package)?

**Comment by CohenCyril** [comment]
When I return from vacations

**Comment by proux01** [comment]
Sure, no hurry (I also have a few refinements to add in binrat, so maybe would it be also worth waiting for that PR).

**Pull request merged**
